### PR TITLE
upgrade to 4.0.3

### PR DESCRIPTION
**Pull request by sunyi000**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sunyi000** [comment]
@conda-forge-admin please rerender

**Comment by sunyi000** [comment]
@raivivek could you please help here? python-javabridge v4.0.3 is required by cellprofiler4.1.3 but I couldn't get this one work

Also, looks like  the other one cellprofiler-core 4.1.3 have conflicts as well..

thanks very much

**Comment by bgruening** [comment]
@conda-forge-admin please rerender

**Comment by bgruening** [comment]
@conda-forge-admin please rerender

**Pull request merged**
